"""crea tablas base

Revision ID: b34421af0d41
Revises: 
Create Date: 2025-12-01 02:26:59.045946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b34421af0d41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_restaurante', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio_km', sa.Float(), nullable=False),
    sa.Column('precio_base', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ubicacion_entrega', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio_delivery', sa.Float(), nullable=False),
    sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('url_imagen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('plato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['plato_id'], ['plato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle')
    op.drop_table('plato')
    op.drop_table('pedido')
    op.drop_table('delivery')
    op.drop_table('configuracion')
    op.drop_table('categoria')
    # ### end Alembic commands ###
