"""agregar campos created_at y updated_at

Revision ID: c5434475bb6c
Revises: b34421af0d41
Create Date: 2025-12-02 00:39:06.027074

"""
from typing import Sequence, Union
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5434475bb6c'
down_revision: Union[str, Sequence[str], None] = 'b34421af0d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columnas como nullable primero
    op.add_column('categoria', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categoria', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('configuracion', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('configuracion', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('detalle', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('detalle', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('pedido', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pedido', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('plato', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('plato', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Establecer valores por defecto para registros existentes
    now = datetime.now(timezone.utc)
    op.execute(f"UPDATE categoria SET created_at = '{now}', updated_at = '{now}' WHERE created_at IS NULL")
    op.execute(f"UPDATE configuracion SET created_at = '{now}', updated_at = '{now}' WHERE created_at IS NULL")
    op.execute(f"UPDATE delivery SET created_at = '{now}', updated_at = '{now}' WHERE created_at IS NULL")
    op.execute(f"UPDATE detalle SET created_at = '{now}', updated_at = '{now}' WHERE created_at IS NULL")
    op.execute(f"UPDATE pedido SET created_at = '{now}', updated_at = '{now}' WHERE created_at IS NULL")
    op.execute(f"UPDATE plato SET created_at = '{now}', updated_at = '{now}' WHERE created_at IS NULL")
    
    # Ahora hacer las columnas NOT NULL
    op.alter_column('categoria', 'created_at', nullable=False)
    op.alter_column('categoria', 'updated_at', nullable=False)
    op.alter_column('configuracion', 'created_at', nullable=False)
    op.alter_column('configuracion', 'updated_at', nullable=False)
    op.alter_column('delivery', 'created_at', nullable=False)
    op.alter_column('delivery', 'updated_at', nullable=False)
    op.alter_column('detalle', 'created_at', nullable=False)
    op.alter_column('detalle', 'updated_at', nullable=False)
    op.alter_column('pedido', 'created_at', nullable=False)
    op.alter_column('pedido', 'updated_at', nullable=False)
    op.alter_column('plato', 'created_at', nullable=False)
    op.alter_column('plato', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plato', 'updated_at')
    op.drop_column('plato', 'created_at')
    op.drop_column('pedido', 'updated_at')
    op.drop_column('pedido', 'created_at')
    op.drop_column('detalle', 'updated_at')
    op.drop_column('detalle', 'created_at')
    op.drop_column('delivery', 'updated_at')
    op.drop_column('delivery', 'created_at')
    op.drop_column('configuracion', 'updated_at')
    op.drop_column('configuracion', 'created_at')
    op.drop_column('categoria', 'updated_at')
    op.drop_column('categoria', 'created_at')
    # ### end Alembic commands ###
